### ISSUE TITLE
您好，想问一下您初始的4个数据集的list格式是什么

### ISSUE THREAD

**Issue by silvercherry** [taylover-pei/SSDG-CVPR2020#12]
我现在是每一张图片一个，但好像是有问题，您能不能分享一下初始4个集的list形式？
就是generate_label.py需要的格式

**Comment by taylover-pei** [comment]
The format is just like this:

[
{
"photo_path": your photo path,
"photo_label": 0 for fake and 1 for real,
"photo_belong_to_video_ID": 0,1,2,3,4
}
]
