### ISSUE TITLE
Why feature is normalised by square root of norm?

### ISSUE THREAD

**Issue by hetul-patel** [taylover-pei/SSDG-CVPR2020#14]
Hi. As mentioned in paper you normalise feature using l2 norm. But in your code you devide features by square root of norm multiplied by √2. Can you share your idea behind this approach ?

![Screenshot_20201028-161148.png](https://user-images.githubusercontent.com/14092038/97425943-c93ccc80-1938-11eb-85d8-2e749cca4166.png)

**Comment by taylover-pei** [comment]
Sorry for answering late. 

This is a trick to make the effect of normalization better.

**Comment by alvarobasi** [comment]
Hi! Would you mind explain further the reason of this operation? Can't find anything similar on the literature. Thanks!
