### ISSUE TITLE
数据预处理

### ISSUE THREAD

**Issue by FIRE-MOS** [taylover-pei/SSDG-CVPR2020#17]
第一个问题：请问预处理的流程是不是将每个视频的所有帧都提取出来保存然后再训练，
还是说一边提取一边训练；

第二个问题：比如一个视频10秒钟，30帧每秒的话，总共就是300帧
我需要都保存还是只保存一部分。

非常希望能够得到您的回复

**Comment by taylover-pei** [comment]
全部提取完毕再训练
