### ISSUE TITLE
batch hardest triplet loss code error

### ISSUE THREAD

**Issue by wizyoung** [taylover-pei/SSDG-CVPR2020#2]
In your batch hardest triplet loss code, the margin is hard-coded with 0.1.
https://github.com/taylover-pei/SSDG-CVPR2020/blob/master/loss/hard_triplet_loss.py#L50

the value 0.1 should be replaced with self.margin.

**Comment by taylover-pei** [comment]
Thanks for your suggestion, I will modify it.
