### ISSUE TITLE
Question about data prepare

### ISSUE THREAD

**Issue by woxue** [taylover-pei/SSDG-CVPR2020#3]
Figure 4. Grad-CAM [32] visualizations in your paper show some of the input images.
I notice that you used not only the face map but part of the background, could you please tell me the detail about data processing.When I crop the face with detected bbox, no background will be left.
Thx for your great job~

**Comment by taylover-pei** [comment]
You can appropriately increase the border of the detected bbox so that it can contain the background area. 

More details can be found in 
https://github.com/YYuanAnyVision/mxnet_mtcnn_face_detection/blob/b56065418b63a971fcf4f8f35d058513b0ce6cbf/main.py#L22
