### ISSUE TITLE
How to get Public dataset?

### ISSUE THREAD

**Issue by joongkyunKim** [taylover-pei/SSDG-CVPR2020#5]
Hi, i have researched face anti spoofing area. 
I got Oulu-NPU & ReplayAttack dataset, but i couldn't get MSU-MFSD & CASIA-MFSD dataset. 
In the case of MSU-MFSD dataset, i send agreement several times but there is no reply...
In the case of CASIA-MFSD dataset, i want to upload agreement on website(http://www.cbsr.ia.ac.cn/images/xyz/AgreementUpload.aspx) but failed every time with no reasons. 
So, Can you tell me how to get the dataset?(MSU-MFSD, CASIA-MFSD)

**Comment by taylover-pei** [comment]
Hi, I suggest you to directly send an e-mail to the authors for asking the database.
